### ISSUE TITLE
REP01 Human Monthly Morbidity and Mortality Report - Missing Use Archived data 

### ISSUE THREAD

**Issue by TheTommyLee** [EIDSS/EIDSS7#182] opened 2019-07-15 15:53 UTC
**Summary**
Use archive data box is missing from report form

**To Reproduce**
1. Log in as adamanders
2. Go to 4 in script
3. Click on 

**Expected behavior**
Use archive data box should be displayed and marked unchecked

**Screenshots**

**Additional details:**
 - Build: 83.3
 - Script title (enter ad hoc if not script-based): REP01
![Screenshot (28)](https://user-images.githubusercontent.com/52924423/61229890-fe4aee80-a6f6-11e9-86d4-7072c202f712.png)

**Issue severity (Optional)**
Severity (critical, major, minor, low):

**Additional context**

**Comment by jkkannan** [comment] 2019-07-15 17:55
Duplicate of #173

**Closed** 2021-01-25 16:32 UTC
Labels: Build 83.3, bug, duplicate
