### ISSUE TITLE
Disease Report Summary Report Type Missing

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#83] opened 2019-07-10 13:47 UTC
**Summary**
In the disease report summary tab, the field noting report type was missing. 

**To Reproduce**
1. Log in as russellpeters
2. Go to Human Person
3. Click on Disease Report Summary

**Expected behavior**
A field for report type should have been there and it should have been prepopulated with the word "passive." 
**Screenshots**
![image](https://user-images.githubusercontent.com/52708365/60974203-88055100-a2de-11e9-804d-5d22e974b887.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HPS07

**Issue severity**
Severity (critical, major, minor, low): Minor

**Additional context**

**Comment by christhompson17** [comment] 2019-07-10 15:12
The test scenario requires clicking on the carrot to expand "Disease Report Summary", not the label. In the screenshot, the carrot has not been clicked, as it still is pointing down. Recommend closing, as opposed to listing as a script error since the description is open to interpretation and the issue is relatively minor.

**Closed** 2019-07-10 18:02 UTC
Labels: Build 81.0
