### ISSUE TITLE
Entry of Brucellosis into the search bar does not display samples 

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#51] opened 2019-07-09 15:20 UTC
**Summary**
Entry of Brucellosis into the search bar does not display samples 

**To Reproduce**
1. Log in as ednakrabappel
2. Go to Laboratory>Samples

Step 1. Select Laboratory >Samples. to display samples tab.
Step 2. Enter Search bar Brucellosis.
Step 3. The system does not display any samples.

![image](https://user-images.githubusercontent.com/52667706/60900756-bb8e9f80-a23a-11e9-89da-97a584dd350a.png)

**Expected behavior**
The search displays only Brucellosis samples.

Screenshots**
Above

**Additional details:**
 - Build: 77
 - Script title:  Lab10, Transfer a Sample

**Issue severity**
Severity:  Major

**Additional context**
N/A

**Comment by jkkannan** [comment] 2019-07-09 16:02
Duplicate of #30; only difference is different username.

**Comment by jkkannan** [comment] 2019-07-12 13:54
Closing out as duplicate

**Closed by jkkannan** 2019-07-12 13:54 UTC
Labels: Build 79.0, bug, duplicate

**Comment by Chavez34** [comment] 2019-07-12 18:12
I am receiving these reports to my personal email / please discontinue.
Thanks,
Lawrence Chavez

Sent from my iPhone

> On Jul 12, 2019, at 9:54 AM, jkkannan <notifications@github.com> wrote:
> 
> Closed #51.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
____________________________________________________________
Sad News For Meghan Markle And Prince Harry
track.volutrk.com
http://thirdpartyoffers.juno.com/TGL3141/5d28cd7e17ccc4d7c62cbst02duc
