### ISSUE TITLE
The list of reasons for not taking a sample is in English, and the field "outcome" is also in English.

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#760] opened 2023-06-14 13:26 UTC
**Summary**
The list of reasons for not taking a sample is in English, and the field "outcome" is also in English.

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: Maka tsilosani
Build: 
Severity (MANDATORY): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/41ce09fc-6de6-439f-8486-e9e303b4cdf2)
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/f472dbbe-74c0-4ed2-834b-6b301b8a0d06)

**Additional context**

**Comment by herashchenkoa** [comment] 2023-12-11 21:09
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment] 2023-12-21 19:55
The problem has been resolved, This issue is closed

**Comment by herashchenkoa** [comment] 2024-01-16 19:58
Based on the user's feedback above, the issue is closed.

**Closed by herashchenkoa** 2024-01-16 19:58 UTC
Labels: bug, Ready for Re-test
