### ISSUE TITLE
Lazika is the first in the list of regions, and we don't have such a region! There is no LASIK in Georgian

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#534] opened 2023-04-18 10:51 UTC
**Summary**
Lazika is the first in the list of regions, and we don't have such a region! There is no LASIK in Georgian

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 
Severity (optional): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**
There is no LASIK in Georgian 

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/232754141-999ba981-3db6-461a-840a-a369747bb030.png)

**Additional context**

**Comment by jkkannan** [comment] 2023-04-20 13:23
This region appears to have been created by a tester based on the HASC Code (123) and having no rayons.  It was deleted from the list of Administrative Units this morning. Closing issue as not a bug.

**Closed by jkkannan** 2023-04-20 13:23 UTC
Labels: Investigation, Not bug
