### ISSUE TITLE
Minor script issue

### ISSUE THREAD

**Issue by tonihudson06** [EIDSS/EIDSS7#217] opened 2019-10-08 13:32 UTC
**Summary**
Script HPS12 notes that three human aggregate results should be displayed but four are displayed

**To Reproduce**
1. Log in as marinasmith
2. Go to Human--> Aggregate Disease Report
3. Enter search values; clear rayon

**Expected behavior**
Three human aggregate disease reports from Kakheti region are displayed

**Screenshots**

**Additional details:**
 - Build:
 - Script title (enter ad hoc if not script-based): HPS12

**Issue severity (Optional)**
Severity (critical, major, minor, low): Minor

**Additional context**

**Comment by aatmns** [comment] 2019-10-08 18:15
Not able to reproduce in the testing environment.
Three requested human aggregate reports from 7/1/2019 in Telavi (rayon), Gurjaani, and Akhmeta were available:
![217-1](https://user-images.githubusercontent.com/32458032/66421540-0e145f00-e9d6-11e9-8d64-85bdd71f024e.PNG)

**Comment by jkkannan** [comment] 2019-10-08 18:34
Closing because not reproducible; see comment above.

**Closed by jkkannan** 2019-10-08 18:34 UTC
Labels: Build 98.0, Script
