### ISSUE TITLE
GG lang Country list in Country filed is not translated on Person Window - Employment tab

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#642] opened 2023-06-06 09:22 UTC
**Summary**
GG lang Country list in Country filed is not translated on Person Window - Employment tab

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: 
Build: 7.0.354.12
Severity (MANDATORY): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/e1d33c76-2ab8-4236-a6e8-0044add92936)

**Additional context**

**Comment by herashchenkoa** [comment] 2023-12-11 21:05
The issue has been addressed in EIDSS Release v7.0.411. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment] 2023-12-21 19:44
The problem has been resolved, This issue is closed

**Comment by herashchenkoa** [comment] 2024-01-16 19:58
Based on the user's feedback above, the issue is closed.

**Closed by herashchenkoa** 2024-01-16 19:58 UTC
Labels: bug, Ready for Re-test
