### ISSUE TITLE
Bardcode number identified is not found using search control 

### ISSUE THREAD

**Issue by Chavez34** [EIDSS/EIDSS7#94] opened 2019-07-10 14:48 UTC
**Summary**

Bardcode number identified is not found using search control (i.e. no results).

**To Reproduce**
1. Log in as troymcclure
2. Go to Laboratory
3. Click on Transferred to display Transferred tab
4. Click on search field
5. Scan barcode and system display identification number in the search field.
6. Select search field - no results are displayed.

**Expected behavior**
Barcode number identified is found using search control

**Screenshots**
![image](https://user-images.githubusercontent.com/52667706/60978279-e3473b80-a2fe-11e9-833c-aa9462df3a63.png)

**Additional details:**
 - Build: 81
 - Script title: LAB19, Search for a transfer sample using barcodes.

**Issue severity**
Severity: Major

**Additional context**
None

**Comment by aatmns** [comment] 2019-07-22 14:59
Not able to reproduce. 
The system correctly entered barcode value from the barcode scanner.
Recommend to close this defect.

**Closed** 2021-01-25 16:34 UTC
Labels: Build 81.0, GAT data issue, bug
