### ISSUE TITLE
VAS12 - Veterinary Access Surveillance Session - Printing error

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#338] opened 2022-05-25 17:34 UTC
**Summary**
Veterinary Access Surveillance Session - Printing error for printing of search results - error Reporting Services Error

**Details**
Script ID (or enter ad hoc if ad hoc): VAS12
Username: Keda Rayon
Severity (optional): M

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Search Results
2. Click on Print

**Expected behavior**
Report is printed

**Screenshots**

**Additional context**

**Comment by EBH2001** [comment] 2022-05-25 21:18
Reproducible in PreGAT, build 267.21
![image](https://user-images.githubusercontent.com/16134915/170368952-0d5cc584-1c21-4fa5-9c81-3e059cdfd255.png)

**Comment by aatmns** [comment] 2022-08-10 15:01
The issues is resolved.
The printout displayed as designed.
![image](https://user-images.githubusercontent.com/32458032/183938169-f3cb238e-d072-409f-abda-0931054823f7.png)

**Comment by NatalieShapiro** [comment] 2022-08-18 20:12
I can see the print results but the header bleeds onto the print preview screen so I can't exit out (I have to click print). Minor since most people will just print. I tried this on my UNET and MAC and with different browsers. Also I technically can't test printing. It allowed me to generate a PDF. See screenshot
<img width="1377" alt="Screen Shot 2022-08-18 at 4 09 29 PM" src="https://user-images.githubusercontent.com/105503558/185485880-07b9f5c9-bad1-41c8-a508-ea18ccbb0878.png">

**Comment by NatalieShapiro** [comment] 2022-08-25 12:53
@jkkannan Clarification:

Although I can see the print preview screen (which wasn't available before), there is a UI issue where the header of the print pop-up is cut off so you can't exit out. You must press print. I consider this a related (minor) issue so I didn't close out the bug. I recommend fixing the UI issue so that you can exit if you don't want to print.

**Comment by jkkannan** [comment] 2022-08-26 12:49
Feedback from tester: "Just retested. Zoom is at 100%. I tried on Chrome and Edge on my UNET and the header is still cut off. That being said, I could use the diagonal arrows to change the size of the pop-up. However, I think the default should be set smaller so you don't have to do that.

I tried on my Mac (Chrome) and it was still large but I could exit out (barely). Minor but could potentially hinder user experience. It's fine if you decide to close it out."
Will close.

**Closed by jkkannan** 2022-08-26 12:49 UTC
Labels: bug, Minor, 267.21
