### ISSUE TITLE
A new session summary form fails to display with autopopulated data for status (in progress) and session star date) and unable to test the reaming steps of the script. 

### ISSUE THREAD

**Issue by shahina77** [EIDSS/EIDSS7#49] opened 2019-07-09 15:15 UTC
**Summary**
A new session summary form should display with autopopulated data for status (in progress) and session star date) and unable to test the reaming steps of the script. 

**To Reproduce**
1. Log in as 
2. Go to 
3. Click on 

**Expected behavior**
A new session summary form should display with autopopulated data should display. 
Screenshots**

**Additional details:**
 - Build: 80
 - Script title (enter ad hoc if not script-based):

**Issue severity**
Severity (critical, major, minor, low):
Critical
**Additional context**
VEC01
[VEC01.zip](https://github.com/EIDSS/EIDSS7/files/3373647/VEC01.zip)

**Comment by aatmns** [comment] 2019-07-22 16:29
7/22/19 
Retested the entire VEC01 scenario.
Not able to reproduce. The system populated properly the status value and all data needed were entered.
Recommend closing the defect as not able to reproduce.

**Closed** 2021-01-25 16:35 UTC
Labels: Build 79.0, bug
