### ISSUE TITLE
VEC03

### ISSUE THREAD

**Issue by CarolChapman1** [EIDSS/EIDSS7#373] opened 2022-05-26 17:28 UTC
**Summary**
Sample details page froze multiple times when trying to enter Sample Type-drop down menu didn't not have selections- could not save or cancel or x out.

**Details**
Script ID (or enter ad hoc if ad hoc):
Username: 
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aatmns** [comment] 2022-05-26 17:58
Unable to reproduce in preGAT environment.
Able to create a simple Vector Session without Detailed or Aggregate collections.
![373-1-simple record](https://user-images.githubusercontent.com/32458032/170547115-ad3b9c92-d451-4198-9669-e99cf09a8b1c.png)

Able to created a Vector Session with Detailed Collection:
![373-2-session with detailed](https://user-images.githubusercontent.com/32458032/170547172-3b0606ea-083b-4937-a687-5310b4a07ef8.png)

Able to create a Vector Session with Detailed and Aggregate Collections:
![373-3-session with detailed and aggregate](https://user-images.githubusercontent.com/32458032/170547244-5c68fcd5-5d72-4681-89aa-a42a8683dd79.png)
![373-3-session with detailed and aggregated](https://user-images.githubusercontent.com/32458032/170547629-06481ce2-459c-40c7-966d-ec237df20c6a.png)
![373-3-session with detailed and aggregatea](https://user-images.githubusercontent.com/32458032/170547643-b4b72466-9b83-4c5b-9556-76f5c52b8f77.png)

**Comment by aatmns** [comment] 2022-05-26 22:35
Unable to reproduce stated defect at the GAT environment.
Was able to create multiple samples and fields in a vector surveillance session.

**Comment by karlasomera** [comment] 2022-08-01 15:58
Under this issue- on the external environment the entering the vector surveillance session had no issues to add a detail collection samples.  Able to run the script with no issues.  

Under GAT environment, no issues encountered when adding a new Vector Surveillance Session and was able to add detail collection data.

Recommend closing out this bug.

**Closed** 2022-08-01 19:12 UTC
Labels: bug, GAT deploy/config, 269.6, can't reproduce in GAT
