### ISSUE TITLE
Human Disease Report Screen Region Not Prepopulated

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#33] opened 2019-07-09 14:08 UTC
**Summary**
The human disease report screen was not prepopulated with region.

**To Reproduce**
1. Log in as: Russell Peters, Epidemiologist
2. Go to: Human 
3. Click on: Disease Report

**Expected behavior**
The search form region and Rayon were not prepopulated

Screenshots**

**Additional details:**
 - Build: 79.0
 - Script title (enter ad hoc if not script-based): HSP03 

**Issue severity**
Severity (critical, major, minor, low): Low

**Additional context**

**Comment by jkkannan** [comment] 2019-07-09 14:17
Duplicate of #13

**Comment by jkkannan** [comment] 2019-07-12 13:54
Closing as duplicate of #7

**Closed by jkkannan** 2019-07-12 13:54 UTC
Labels: bug, duplicate
