### ISSUE TITLE
VAS20 - Veterinary Active Surveillance - blocked Campaign ID search field (unable to connect session and campaign)

### ISSUE THREAD

**Issue by AnnaSwiatecka** [EIDSS/EIDSS7#351] opened 2022-05-25 19:09 UTC
**Summary**
Veterinary Active Surveillance - blocked Campaign ID search field (unable to connect session and campaign)

**Details**
Script ID (or enter ad hoc if ad hoc): VAS20
Username:  Adjara RVO
Severity (optional): S

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Session Information
2. Click on Campaign ID

**Expected behavior**
Connect to the campaign

**Screenshots**

**Additional context**

**Comment by aatmns** [comment] 2022-08-10 19:40
The issue is resolved.
Attached standalone veterinary AS Session is retained in the Campaign record:
![image](https://user-images.githubusercontent.com/32458032/184005550-3f8226c3-7f45-4466-b54a-5b5586e9b56e.png)

**Comment by NatalieShapiro** [comment] 2022-08-18 20:30
I couldn't create a campaign ID. I will request Karla to try this one tomorrow.

**Comment by karlasomera** [comment] 2022-08-19 13:23
Able to create a new active Surveillance Session and link it to the Active Surveillance Campaign.  System behave as expected.  Recommend closing out this bug.

**Closed** 2022-08-19 15:21 UTC
Labels: bug, Minor, 267.21
