### ISSUE TITLE
Impossible to create aliquot from Laboratory. After click save button system loading long time

### ISSUE THREAD

**Issue by Elisomamisashvili** [EIDSS/EIDSS7#870] opened 2023-11-30 11:26 UTC
### Country

Georgia

### Username

ElisoMamisashvili

### Build number

7.0.402

### Language

Georgian

### Severity (MANDATORY)

3 - Medium

### Module

Laboratory

### Description of the steps to reproduce

Laboratory
Sample
Registration new Sample
Create new aliquot on aliquots/derivatives popup
[Save]
[New Microsoft Word Document.docx](https://github.com/EIDSS/EIDSS7/files/13512084/New.Microsoft.Word.Document.docx)

**Comment by herashchenkoa** [comment] 2024-06-14 17:27
The issue has been addressed in EIDSS Release v7.0.480. Please verify to confirm that the issue was resolved.

**Comment by herashchenkoa** [comment] 2024-06-27 08:06
Based on the user's feedback, the issue is resolved, and the bug is closed.

**Closed by herashchenkoa** 2024-06-27 08:06 UTC
Labels: Ready for Re-test
