### ISSUE TITLE
English version human>person>address>region  Abkhazia >Rayon QA9 and QA99  what does it mean

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#529] opened 2023-04-13 11:57 UTC
**Summary**
English version human>person>address>region  Abkhazia >Rayon QA9 and QA99  what does it mean
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): Function
Username: bakuradze
Build: 
Severity (optional): 

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… English version human>person>address>region  Abkhazia >Rayon QA9 and QA99 
2. Click on… 

**Expected behavior**

**Screenshots**
![abx](https://user-images.githubusercontent.com/128576431/231751421-7da103ad-4eec-43d7-9783-54953a48209a.PNG)

**Additional context**

**Comment by aherashchenko** [comment] 2023-05-03 13:09
The values have been created during UAT Trainings for training purposes. Both of them were deleted via the Administrative Units,

**Comment by jkkannan** [comment] 2023-05-10 13:53
Closing as not a bug.

**Closed by jkkannan** 2023-05-10 13:53 UTC
Labels: Investigation, Not bug
