### ISSUE TITLE
Human>Person> Personal ID Type 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#502] opened 2023-04-10 11:07 UTC
**Summary**
In Personal ID Type Passport is not translated 
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc): Function
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: bakuradze
Build: 7.0.343.47
Severity (optional): important

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… Human>Person> 
2. Click on… Personal ID Type 

**Expected behavior**
Passport should be translated ,, პასპორტის ნომერი“

**Screenshots**
If applicable, add screenshots to help explain your problem.  Please blur or cover any personally identifiable information in any screenshots.
![passport translation](https://user-images.githubusercontent.com/128576431/230890439-7d358f9a-797b-46e1-9bae-2104021ad7e2.PNG)

**Additional context**

**Comment by jkkannan** [comment] 2023-04-20 13:24
Field was not translated as it was entered only in English during training. Deleted value from list of Personal ID Types. Closing as not a bug.

**Closed by jkkannan** 2023-04-20 13:24 UTC
Labels: Investigation, Not bug, 343.47

**Comment by bakuradzebakuradze** [comment] 2023-04-29 15:52
fixed
