### ISSUE TITLE
Human Person Data not prepopulated

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#82] opened 2019-07-10 13:39 UTC
**Summary**
Fields Region and Rayon on Search for Person screen were not prepopulated as indicated in script. Additionally last name field was prepopulated with the wrong last name (Prepopulated with Taylor).

**To Reproduce**
1. Log in as russellpeters
2. Go to Human Person, 
3. Click on N/A

**Expected behavior**
Region and Rayon should have been prepopulated; all other fields remain blank.

**Screenshots**

![image](https://user-images.githubusercontent.com/52708365/60973604-6f486b80-a2dd-11e9-9152-17a6b42a9da9.png)

**Additional details:**
 - Build: 81
 - Script title (enter ad hoc if not script-based): HPS 07

**Issue severity**
Severity (critical, major, minor, low): Low

**Additional context**

**Comment by jkkannan** [comment] 2019-07-10 14:03
Duplicate of previously reported issue in VPS and HPS regarding region/rayon not being prepopulated.

**Closed** 2019-07-10 18:01 UTC
Labels: Build 81.0, bug, duplicate
